############################################
# Core Certificate Outputs
############################################

output "certificate_arn" {
  description = "ARN of the ACM certificate."
  value       = aws_acm_certificate.this.arn
}

output "certificate_id" {
  description = "ID of the ACM certificate."
  value       = aws_acm_certificate.this.id
}

output "certificate_type" {
  description = "Certificate type managed by the module."
  value       = local.certificate_type
}

output "domain_name" {
  description = "Primary domain name associated with the ACM certificate."
  value       = aws_acm_certificate.this.domain_name
}

output "subject_alternative_names" {
  description = "Subject alternative names associated with the certificate."
  value       = aws_acm_certificate.this.subject_alternative_names
}

output "status" {
  description = "Current ACM certificate status."
  value       = aws_acm_certificate.this.status
}


############################################
# DNS Validation Outputs
############################################

output "domain_validation_options" {
  description = "DNS validation records generated by ACM for PUBLIC certificates."
  value       = aws_acm_certificate.this.domain_validation_options
}

output "validation_record_fqdns" {
  description = "Route53 validation record FQDNs created by this module."

  value = [
    for record in aws_route53_record.validation :
    record.fqdn
  ]
}


############################################
# Metadata
############################################

output "tags" {
  description = "Tags applied to the ACM certificate."
  value       = local.tags
}